config_editor:
sensor:
  - platform: rest
    name: "ETA Abgas Temperatur"
    scan_interval: 120
    resource: http://192.168.178.10:8080/user/var//48/10391/0/11110/0
    value_template: '{{ value_json.eta.value["@strValue"] | replace(",", ".") | float }}'
    unit_of_measurement: "°C"
  - platform: rest
    name: "ETA Warmwasser"
    scan_interval: 120
    resource: http://192.168.178.10:8080/user/var//120/10251/0/11129/0
    value_template: '{{ value_json.eta.value["@strValue"] | replace(",", ".") | float }}'
    unit_of_measurement: "°C"
  - platform: rest
    name: "ETA Ladezustand"
    scan_interval: 120
    resource: http://192.168.178.10:8080/user/var//120/10251/0/0/12528
    value_template: '{{ value_json.eta.value["@strValue"] | replace(",", ".") | float }}'
    unit_of_measurement: "%"
  - platform: rest
    name: "ETA Puffer oben"
    scan_interval: 120
    resource: http://192.168.178.10:8080/user/var//120/10251/0/11153/0
    value_template: '{{ value_json.eta.value["@strValue"] | replace(",", ".") | float }}'
    unit_of_measurement: "°C"
  - platform: rest
    name: "ETA Puffer mitte"
    scan_interval: 120
    resource: http://192.168.178.10:8080/user/var//120/10251/0/11053/0
    value_template: '{{ value_json.eta.value["@strValue"] | replace(",", ".") | float }}'
    unit_of_measurement: "°C"
  - platform: rest
    name: "ETA Puffer unten"
    scan_interval: 120
    resource: http://192.168.178.10:8080/user/var//120/10251/0/11155/0
    value_template: '{{ value_json.eta.value["@strValue"] | replace(",", ".") | float }}'
    unit_of_measurement: "°C"
  - platform: rest
    name: "ETA Aussentemperatur"
    scan_interval: 120
    resource: http://192.168.178.10:8080/user/var//48/10241/0/0/12197
    value_template: '{{ value_json.eta.value["@strValue"] | replace(",", ".") | float }}'
    unit_of_measurement: "°C"
  - platform: rest
    name: "ETA Vorlauftemperatur Heizkreis"
    scan_interval: 120
    resource: http://192.168.178.10:8080/user/var//120/10101/0/11060/0
    value_template: '{{ value_json.eta.value["@strValue"] | replace(",", ".") | float }}'
    unit_of_measurement: "°C"
  - platform: rest
    name: "ETA Heizung"
    scan_interval: 120
    resource: http://192.168.178.10:8080/user/var//120/10101/0/0/12090
    value_template: '{{ value_json.eta.value["@strValue"]}}'
  - platform: rest
    name: "ETA Zündung Automatik aktiviert"
    scan_interval: 120
    resource: http://192.168.178.10:8080/user/var//48/10391/0/0/13205
    value_template: '{{ value_json.eta.value["@strValue"]}}'
  - platform: rest
    name: "ETA Zündung"
    scan_interval: 120
    resource: http://192.168.178.10:8080/user/var//48/10391/0/0/12163
    value_template: '{{ value_json.eta.value["@strValue"]}}'
  - platform: rest
    name: "ETA Frischwasser"
    scan_interval: 120
    resource: http://192.168.178.10:8080/user/var//79/10531/0/11148/2002
    value_template: '{{ value_json.eta.value["@strValue"]}}'
  - platform: rest
    name: "ETA Kessel"
    scan_interval: 120
    resource: http://192.168.178.10:8080/user/var//48/10391/0/11108/2002
    value_template: '{{ value_json.eta.value["@strValue"]}}'
  - platform: rest
    name: "ETA Anzahl der automatischen Zündungen"
    scan_interval: 120
    resource: http://192.168.178.10:8080/user/var//48/10391/0/0/12018
    value_template: '{{ value_json.eta.value["@strValue"]}}'
